#!/usr/bin/env python3

# pySerial required!

def run_tests(ser, nbytes):
    pass

#
# main procedue
#

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-d', '--device', type=str, default='/dev/ttyUSB0', help='USB device (default: /dev/ttyUSB0)')
parser.add_argument('-t', '--test', type=int, help='Test memory (write and verify the whole memory), passing the number of bytes to test')
args = parser.parse_args()

print('Loading serial library...')
import serial

with serial.Serial(args.device, 38400, timeout=1) as ser:
    ser.write(b'r 0\r\n')
    ser.flush()
    print(ser.readline())
    print(ser.readline())
    print(ser.readline())

    #
    # run tests
    #
    if args.test != None:
        run_tests(ser, args.test)

    ser.close()

