#ifndef SDCARDSTAGE_H_
#define SDCARDSTAGE_H_

typedef enum {
    SD_MCU_SETUP   = 0x0, SD_RESET, SD_GO_IDLE, SD_IF_COND, SD_INIT,
    SD_GET_OCR     = 0x10,
    SD_READ_OK     = 0x20, SD_READ_REJECTED, SD_READ_TIMEOUT, SD_READ_CRC_FAILED,
    SD_WRITE_OK    = 0x30, SD_WRITE_REJECTED, SD_WRITE_TIMEOUT, SD_WRITE_DATA_REJECTED, SD_WRITE_DATA_TIMEOUT,
    SD_NOT_INITIALIZED = 0xff,
} SDCardStage;

#endif
