#ifndef EMULATOR_COLORS_HH
#define EMULATOR_COLORS_HH

#define COLOR_TERMINAL   COLOR_PAIR(0)
#define COLOR_REGULAR    COLOR_PAIR(1)
#define COLOR_FIELD      COLOR_PAIR(2)
#define COLOR_DISABLED   COLOR_PAIR(3)
#define COLOR_MEMORY     COLOR_PAIR(4)
#define COLOR_DIALOG     COLOR_PAIR(6)
#define COLOR_BREAKPOINT COLOR_PAIR(7)
#define COLOR_ADDRESS    COLOR_PAIR(8)

#endif //EMULATOR_COLORS_HH