#ifndef EMULATOR_COLORS_HH
#define EMULATOR_COLORS_HH

#define COLOR_TERMINAL COLOR_PAIR(0)
#define COLOR_REGULAR  COLOR_PAIR(1)
#define COLOR_FIELD    COLOR_PAIR(2)
#define COLOR_DISABLED COLOR_PAIR(3)

#endif //EMULATOR_COLORS_HH